spring:
  datasource:
    url: jdbc:mysql://124.70.206.207:3306/javaee?serverTimezone=UTC
    username: javaee
    password: 666666wW
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true